// // // src/app/layout.tsx
// // import type { Metadata } from 'next';
// // import '@/styles/globals.css';
// // import Sidebar from '@/components/Sidebar';
// // export const metadata: Metadata = {
// //   title: 'Create Next App',
// //   description: 'Generated by create next app',
// // };
// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="pt-br" data-theme="black">
// //       <body>
// //         <div className="flex flex-col lg:flex-row w-screen h-screen min-h-full">
// //           <div className="flex bg-accent w-screen h-auto p-4 lg:p-2 lg:w-[15%] lg:min-w-[15%] lg:h-screen lg:min-h-screen">
// //             <Sidebar />
// //           </div>
// //           <div className=" flex bg-accent-content w-screen h-screen p-2 lg:w-[85%] lg:min-w-[85%] lg:min-h-screen lg:p-4">
// //             {children}
// //           </div>
// //         </div>
// //       </body>
// //     </html>
// //   );
// // }

// import type { Metadata } from 'next';
// import '@/styles/globals.css';
// import Sidebar from '@/components/Sidebar';

// export const metadata: Metadata = {
//   title: 'ZionCWB - André Lopes Paiva',
//   description: 'Portfólio profissional de André Lopes Paiva',
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="pt-br" data-theme="black">
//       <body className="min-h-screen bg-base-200">
//         <div className="flex flex-col lg:flex-row w-full h-full">
//           {/* Sidebar Responsiva */}
//           <aside className="bg-accent w-full lg:w-1/5 p-4">
//             <Sidebar />
//           </aside>

//           {/* Conteúdo Principal */}
//           <main className="bg-accent-content flex-1 p-4 overflow-auto">
//             {children}
//           </main>
//         </div>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from 'next';
import '@/styles/globals.css';
import Sidebar from '@/components/Sidebar';

export const metadata: Metadata = {
  title: 'ZionCWB - André Lopes Paiva',
  description: 'Portfólio profissional de André Lopes Paiva',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" data-theme="corporate">
      <body className="min-h-screen bg-base-200">
        <div className="flex flex-col lg:flex-row w-full h-full">
          <aside className="bg-accent w-full lg:w-1/5 p-4">
            <Sidebar />
          </aside>

          <main className="bg-accent-content flex-1 p-4 overflow-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
